### ISSUE TITLE
TimeZoneRegistryImpl NullPointerException

### ISSUE THREAD

**Issue by dschuermann** [dschuermann/ical-import-export#11]
```
AndroidRuntime  E  FATAL EXCEPTION: Thread-10413
  9706         AndroidRuntime  E  java.lang.NullPointerException
  9706         AndroidRuntime  E  at edu.emory.mathcs.backport.java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:769)
  9706         AndroidRuntime  E  at net.fortuna.ical4j.model.TimeZoneRegistryImpl.getTimeZone(TimeZoneRegistryImpl.java:136)
  9706         AndroidRuntime  E  at org.sufficientlysecure.ical.SaveCalendar.run(SaveCalendar.java:85)
  9706         AndroidRuntime  E  at org.sufficientlysecure.ical.ui.dialogs.DialogTools$2.run(DialogTools.java:85)
  9706         AndroidRuntime  E  at java.lang.Thread.run(Thread.java:856)
```

http://sourceforge.net/p/ical4j/discussion/368291/thread/24a3bcf8/

**Comment by dschuermann** [comment]
fixed with https://github.com/dschuermann/ical-import-export/pull/18
