### ISSUE TITLE
Exception DTEND and DURATION cannot both be null for an event.

### ISSUE THREAD

**Issue by dschuermann** [dschuermann/ical-import-export#14]
```
 20907          VEventWrapper  D  VEvent ready to insert into db
 20907          InsertVEvents  D  values: calendar_id=12 dtstart=1295892000000 title=test! rrule=FREQ=YEARLY eventTimezone=Europe/London
 21825      CalendarProvider2  I  dtStart:       1295892000000
 21825      CalendarProvider2  I  dtEnd:         null
 21825      CalendarProvider2  I  all_day:       null
 21825      CalendarProvider2  I  tz:            Europe/London
 21825      CalendarProvider2  I  dur:           null
 21825      CalendarProvider2  I  rrule:         FREQ=YEARLY
 21825      CalendarProvider2  I  rdate:         null
 21825      CalendarProvider2  I  last_date:     null
 21825      CalendarProvider2  I  id:            null
 21825      CalendarProvider2  I  sync_id:       null
 21825      CalendarProvider2  I  ori_id:        null
 21825      CalendarProvider2  I  ori_sync_id:   null
 21825      CalendarProvider2  I  ori_inst_time: null
 21825      CalendarProvider2  I  ori_all_day:   null
 21825          DatabaseUtils  E  Writing exception to parcel
 21825          DatabaseUtils  E  java.lang.IllegalArgumentException: DTEND and DURATION cannot both be null for an event.
 21825          DatabaseUtils  E  at com.android.providers.calendar.CalendarProvider2.validateEventData(CalendarProvider2.java:2554)
 21825          DatabaseUtils  E  at com.android.providers.calendar.CalendarProvider2.insertInTransaction(CalendarProvider2.java:2111)
 21825          DatabaseUtils  E  at com.android.providers.calendar.SQLiteContentProvider.insert(SQLiteContentProvider.java:96)
 21825          DatabaseUtils  E  at android.content.ContentProvider$Transport.insert(ContentProvider.java:201)
 21825          DatabaseUtils  E  at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:148)
 21825          DatabaseUtils  E  at android.os.Binder.execTransact(Binder.java:351)
 21825          DatabaseUtils  E  at dalvik.system.NativeStart.run(Native Method)
 20907          InsertVEvents  E  InsertVEvents
 20907          InsertVEvents  E  java.lang.IllegalArgumentException: DTEND and DURATION cannot both be null for an event.
 20907          InsertVEvents  E  at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
 20907          InsertVEvents  E  at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
 20907          InsertVEvents  E  at android.content.ContentProviderProxy.insert(ContentProviderNative.java:420)
 20907          InsertVEvents  E  at android.content.ContentResolver.insert(ContentResolver.java:866)
 20907          InsertVEvents  E  at org.sufficientlysecure.ical.InsertVEvents.run(InsertVEvents.java:101)
 20907          InsertVEvents  E  at org.sufficientlysecure.ical.ui.dialogs.DialogTools$2.run(DialogTools.java:85)
 20907          InsertVEvents  E  at java.lang.Thread.run(Thread.java:856)
 21825      CalendarProvider2  I  Sending notification intent: Intent { act
```

**Comment by dschuermann** [comment]
fixed with https://github.com/dschuermann/ical-import-export/pull/18
